"""Rule-based (explicitly NOT machine learning) threat predictions for the
SHADOW Predict layer. Every prediction is produced by a plain if/else rule
over already-known signals - there is no trained model, no probabilistic
inference, and no learning from data involved. This is stated in the API
response so it is never mistaken for an AI/ML prediction.
"""
from typing import Any

RULE_BASED_DISCLAIMER = (
    "These predictions are generated by fixed, human-written rules over your "
    "checklist and breach-check answers - not by a machine-learning model."
)


def generate_predictions(signals: dict[str, Any]) -> list[dict]:
    """signals: {
        "breach_count": int | None,
        "has_2fa": bool | None,
        "reuses_password": bool | None,
        "has_old_accounts": bool | None,
    }
    Returns a list of {"prediction_text": str, "confidence_label": str}.
    """
    predictions: list[dict] = []

    breach_count = signals.get("breach_count") or 0
    has_2fa = signals.get("has_2fa")
    reuses_password = signals.get("reuses_password")
    has_old_accounts = signals.get("has_old_accounts")

    if breach_count > 0 and has_2fa is False:
        predictions.append({
            "prediction_text": (
                "Your password appears in known breaches and 2FA is not enabled - "
                "this is a strong credential-stuffing / phishing risk. Attackers "
                "commonly replay breached passwords against other sites you use."
            ),
            "confidence_label": "high",
        })
    elif breach_count > 0:
        predictions.append({
            "prediction_text": (
                "Your password appears in known breaches. Even with 2FA enabled, "
                "consider it compromised and change it wherever it is used."
            ),
            "confidence_label": "medium",
        })

    if reuses_password is True:
        predictions.append({
            "prediction_text": (
                "You reuse this password across multiple accounts - if any one "
                "of those services is breached, all of your accounts sharing it "
                "are at risk of takeover."
            ),
            "confidence_label": "high" if breach_count > 0 else "medium",
        })

    if has_old_accounts is True:
        predictions.append({
            "prediction_text": (
                "You still have old/unused accounts - these are rarely monitored "
                "and increase the attack surface an attacker can use to pivot "
                "into your active accounts (e.g. shared password or recovery email)."
            ),
            "confidence_label": "medium",
        })

    if has_2fa is False and breach_count == 0 and reuses_password is not True:
        predictions.append({
            "prediction_text": (
                "Two-factor authentication is not enabled. No breach was found "
                "for this password, but without 2FA a future leaked or guessed "
                "password would immediately grant full account access."
            ),
            "confidence_label": "low",
        })

    if not predictions:
        predictions.append({
            "prediction_text": (
                "No significant risk signals were found in your current checklist "
                "and breach check. Keep 2FA enabled and avoid reusing passwords."
            ),
            "confidence_label": "low",
        })

    return predictions
