/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        navy: {
          950: "#050b18",
          900: "#0a1428",
          800: "#101f3a",
          700: "#16294d",
        },

        // Landing page palette (dark theme, from Stitch design).
        // Namespaced with `land-` so it never collides with the docs palette.
        land: {
          "on-tertiary": "#68000b",
          "primary-container": "#00d1ff",
          "on-error": "#690005",
          "secondary-fixed": "#5bffa1",
          "secondary-container": "#27ff97",
          "on-primary-container": "#00566a",
          "on-secondary-fixed": "#00210e",
          "on-surface-variant": "#bbc9cf",
          "secondary-fixed-dim": "#00e383",
          "tertiary-fixed-dim": "#ffb3ae",
          "surface-dim": "#0f131f",
          "on-primary-fixed-variant": "#004e60",
          "on-tertiary-container": "#a10017",
          "surface-container-high": "#262a37",
          "tertiary-container": "#ffaaa4",
          error: "#ffb4ab",
          "on-secondary": "#00391d",
          "on-primary": "#003543",
          "on-secondary-fixed-variant": "#00522c",
          "outline-variant": "#3c494e",
          "on-secondary-container": "#00723f",
          "on-tertiary-fixed-variant": "#930014",
          "surface-container": "#1b1f2c",
          secondary: "#f5fff3",
          "on-background": "#dfe2f3",
          "surface-bright": "#353946",
          primary: "#a4e6ff",
          tertiary: "#ffd1ce",
          "surface-container-low": "#171b28",
          "inverse-surface": "#dfe2f3",
          "surface-variant": "#313442",
          background: "#0f131f",
          "on-surface": "#dfe2f3",
          "inverse-primary": "#00677f",
          outline: "#859399",
          "surface-tint": "#4cd6ff",
          "primary-fixed-dim": "#4cd6ff",
          surface: "#0f131f",
          "error-container": "#93000a",
          "surface-container-lowest": "#0a0e1a",
          "tertiary-fixed": "#ffdad7",
          "inverse-on-surface": "#2c303d",
          "on-error-container": "#ffdad6",
          "surface-container-highest": "#313442",
          "on-primary-fixed": "#001f28",
          "primary-fixed": "#b7eaff",
          "on-tertiary-fixed": "#410004",
        },

        // Docs page palette (light theme, from Stitch design).
        // Namespaced with `doc-` so it never collides with the landing palette.
        doc: {
          "on-error": "#ffffff",
          "on-background": "#191c1e",
          "surface-container-lowest": "#ffffff",
          outline: "#727785",
          "primary-container": "#2170e4",
          tertiary: "#924700",
          surface: "#f7f9fb",
          "on-primary-fixed": "#001a42",
          "error-container": "#ffdad6",
          "on-secondary": "#ffffff",
          "on-tertiary-fixed-variant": "#723600",
          "on-tertiary-fixed": "#311400",
          "on-secondary-container": "#5c647a",
          "on-primary-container": "#fefcff",
          "secondary-container": "#dae2fd",
          "secondary-fixed-dim": "#bec6e0",
          background: "#f7f9fb",
          "surface-container-highest": "#e0e3e5",
          "surface-container-high": "#e6e8ea",
          "on-surface": "#191c1e",
          "secondary-fixed": "#dae2fd",
          "on-primary-fixed-variant": "#004395",
          "inverse-on-surface": "#eff1f3",
          "outline-variant": "#c2c6d6",
          "primary-fixed": "#d8e2ff",
          error: "#ba1a1a",
          "tertiary-container": "#b75b00",
          "surface-variant": "#e0e3e5",
          "on-tertiary": "#ffffff",
          "on-error-container": "#93000a",
          "on-secondary-fixed": "#131b2e",
          "inverse-primary": "#adc6ff",
          "tertiary-fixed-dim": "#ffb786",
          "surface-tint": "#005ac2",
          secondary: "#565e74",
          "surface-container": "#eceef0",
          "primary-fixed-dim": "#adc6ff",
          "surface-dim": "#d8dadc",
          "surface-bright": "#f7f9fb",
          "inverse-surface": "#2d3133",
          "tertiary-fixed": "#ffdcc6",
          primary: "#0058be",
          "on-secondary-fixed-variant": "#3f465c",
          "on-primary": "#ffffff",
          "on-surface-variant": "#424754",
          "surface-container-low": "#f2f4f6",
          "on-tertiary-container": "#fffbff",
        },
      },
      borderRadius: {
        "land-full": "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-mobile": "24px",
        "sidebar-width": "280px",
        "content-gap": "48px",
        "section-padding": "64px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "doc-headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "doc-headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "doc-headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "doc-headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "doc-body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "doc-body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "doc-body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "doc-label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
