/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        navy: {
          950: "#050b18",
          900: "#0a1428",
          800: "#101f3a",
          700: "#16294d",
        },

        // Landing page palette (dark theme, from Stitch design).
        // Namespaced with `land-` so it never collides with the docs palette.
        land: {
          "on-tertiary": "#68000b",
          "primary-container": "#00d1ff",
          "on-error": "#690005",
          "secondary-fixed": "#5bffa1",
          "secondary-container": "#27ff97",
          "on-primary-container": "#00566a",
          "on-secondary-fixed": "#00210e",
          "on-surface-variant": "#bbc9cf",
          "secondary-fixed-dim": "#00e383",
          "tertiary-fixed-dim": "#ffb3ae",
          "surface-dim": "#0f131f",
          "on-primary-fixed-variant": "#004e60",
          "on-tertiary-container": "#a10017",
          "surface-container-high": "#262a37",
          "tertiary-container": "#ffaaa4",
          error: "#ffb4ab",
          "on-secondary": "#00391d",
          "on-primary": "#003543",
          "on-secondary-fixed-variant": "#00522c",
          "outline-variant": "#3c494e",
          "on-secondary-container": "#00723f",
          "on-tertiary-fixed-variant": "#930014",
          "surface-container": "#1b1f2c",
          secondary: "#f5fff3",
          "on-background": "#dfe2f3",
          "surface-bright": "#353946",
          primary: "#a4e6ff",
          tertiary: "#ffd1ce",
          "surface-container-low": "#171b28",
          "inverse-surface": "#dfe2f3",
          "surface-variant": "#313442",
          background: "#0f131f",
          "on-surface": "#dfe2f3",
          "inverse-primary": "#00677f",
          outline: "#859399",
          "surface-tint": "#4cd6ff",
          "primary-fixed-dim": "#4cd6ff",
          surface: "#0f131f",
          "error-container": "#93000a",
          "surface-container-lowest": "#0a0e1a",
          "tertiary-fixed": "#ffdad7",
          "inverse-on-surface": "#2c303d",
          "on-error-container": "#ffdad6",
          "surface-container-highest": "#313442",
          "on-primary-fixed": "#001f28",
          "primary-fixed": "#b7eaff",
          "on-tertiary-fixed": "#410004",
        },

        // Docs page palette. Values are CSS variables (see index.css) so the
        // same token names repaint for light vs dark via the `.dark` class.
        doc: {
          "on-error": "var(--doc-on-error)",
          "on-background": "var(--doc-on-background)",
          "surface-container-lowest": "var(--doc-surface-container-lowest)",
          outline: "var(--doc-outline)",
          "primary-container": "var(--doc-primary-container)",
          tertiary: "var(--doc-tertiary)",
          surface: "var(--doc-surface)",
          "on-primary-fixed": "var(--doc-on-primary-fixed)",
          "error-container": "var(--doc-error-container)",
          "on-secondary": "var(--doc-on-secondary)",
          "on-tertiary-fixed-variant": "var(--doc-on-tertiary-fixed-variant)",
          "on-tertiary-fixed": "var(--doc-on-tertiary-fixed)",
          "on-secondary-container": "var(--doc-on-secondary-container)",
          "on-primary-container": "var(--doc-on-primary-container)",
          "secondary-container": "var(--doc-secondary-container)",
          "secondary-fixed-dim": "var(--doc-secondary-fixed-dim)",
          background: "var(--doc-background)",
          "surface-container-highest": "var(--doc-surface-container-highest)",
          "surface-container-high": "var(--doc-surface-container-high)",
          "on-surface": "var(--doc-on-surface)",
          "secondary-fixed": "var(--doc-secondary-fixed)",
          "on-primary-fixed-variant": "var(--doc-on-primary-fixed-variant)",
          "inverse-on-surface": "var(--doc-inverse-on-surface)",
          "outline-variant": "var(--doc-outline-variant)",
          "primary-fixed": "var(--doc-primary-fixed)",
          error: "var(--doc-error)",
          "tertiary-container": "var(--doc-tertiary-container)",
          "surface-variant": "var(--doc-surface-variant)",
          "on-tertiary": "var(--doc-on-tertiary)",
          "on-error-container": "var(--doc-on-error-container)",
          "on-secondary-fixed": "var(--doc-on-secondary-fixed)",
          "inverse-primary": "var(--doc-inverse-primary)",
          "tertiary-fixed-dim": "var(--doc-tertiary-fixed-dim)",
          "surface-tint": "var(--doc-surface-tint)",
          secondary: "var(--doc-secondary)",
          "surface-container": "var(--doc-surface-container)",
          "primary-fixed-dim": "var(--doc-primary-fixed-dim)",
          "surface-dim": "var(--doc-surface-dim)",
          "surface-bright": "var(--doc-surface-bright)",
          "inverse-surface": "var(--doc-inverse-surface)",
          "tertiary-fixed": "var(--doc-tertiary-fixed)",
          primary: "var(--doc-primary)",
          "on-secondary-fixed-variant": "var(--doc-on-secondary-fixed-variant)",
          "on-primary": "var(--doc-on-primary)",
          "on-surface-variant": "var(--doc-on-surface-variant)",
          "surface-container-low": "var(--doc-surface-container-low)",
          "on-tertiary-container": "var(--doc-on-tertiary-container)",
        },
      },
      borderRadius: {
        "land-full": "9999px",
      },
      spacing: {
        gutter: "24px",
        unit: "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-mobile": "24px",
        "sidebar-width": "280px",
        "content-gap": "48px",
        "section-padding": "64px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "doc-headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "doc-headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "doc-headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "doc-headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "doc-body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "doc-body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "doc-body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "doc-label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
