"""SQLAlchemy ORM models. Kept dialect-agnostic (no SQLite-only types) so the
same models work if DATABASE swaps to Postgres later - only the engine URL
in database.py would need to change.
"""
from datetime import datetime, timezone

from sqlalchemy import Column, Integer, String, Float, DateTime, Text, JSON
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class CheckResult(Base):
    """Stores one completed website check, used both as history and as cache."""

    __tablename__ = "check_results"

    id = Column(Integer, primary_key=True, autoincrement=True)
    url = Column(String, nullable=False, index=True)
    domain = Column(String, nullable=False, index=True)
    risk_score = Column(Float, nullable=False)
    verdict = Column(String, nullable=False)  # Safe / Suspicious / Dangerous
    breakdown = Column(JSON, nullable=False)  # per-check pass/fail/unknown details
    ai_explanation = Column(Text, nullable=True)
    ai_explanation_available = Column(Integer, nullable=False, default=1)  # 0/1 bool
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    # Nullable FK to users.id - NULL means an anonymous (not logged in) check.
    # Additive: never required, never changes existing behavior when absent.
    user_id = Column(Integer, nullable=True, index=True)


# --- SHADOW module tables -------------------------------------------------
# Additive tables for the "Digital Shadow" feature set (Map / Predict /
# Protect). These reuse the same SQLite database and declarative Base as
# CheckResult above; nothing here alters the existing table.

class UserProfile(Base):
    """One row per SHADOW user (identified by email). Holds the self-reported
    security checklist collected by the Map layer.
    """

    __tablename__ = "user_profile"

    id = Column(Integer, primary_key=True, autoincrement=True)
    email = Column(String, nullable=False, index=True)
    has_2fa = Column(Integer, nullable=True)  # 0/1/None bool
    reuses_password = Column(Integer, nullable=True)
    has_old_accounts = Column(Integer, nullable=True)
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    # Nullable FK to users.id - NULL means an anonymous SHADOW profile.
    user_id = Column(Integer, nullable=True, index=True)


class BreachSignal(Base):
    """Result of a k-anonymity Pwned Passwords lookup for a user_profile.
    Only the SHA1 prefix (never the raw password or full hash) is stored.
    """

    __tablename__ = "breach_signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_profile_id = Column(Integer, nullable=False, index=True)
    password_hash_prefix = Column(String, nullable=True)  # first 5 hex chars of SHA1
    breach_count = Column(Integer, nullable=False, default=0)
    checked_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))


class Prediction(Base):
    """Rule-based (NOT ML) risk predictions generated by the Predict layer."""

    __tablename__ = "predictions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_profile_id = Column(Integer, nullable=False, index=True)
    prediction_text = Column(Text, nullable=False)
    confidence_label = Column(String, nullable=False)  # e.g. "high", "medium"
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))


class ShadowScoreHistory(Base):
    """Time series of Shadow Score values for a user_profile, so the score's
    trend can be tracked over repeated /shadow/map calls (and, best-effort,
    from /check boosts when a user_profile context is available).
    """

    __tablename__ = "shadow_score_history"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_profile_id = Column(Integer, nullable=False, index=True)
    score = Column(Float, nullable=False)
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    note = Column(String, nullable=True)


# --- Real user accounts ---------------------------------------------------

class User(Base):
    """A real signed-up account. Purely additive: the app remains fully
    usable anonymously - this table only exists to optionally associate
    CheckResult / UserProfile rows with a logged-in person.
    """

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    email = Column(String, nullable=False, unique=True, index=True)
    password_hash = Column(String, nullable=False)
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
